apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: simple-nodejs-app-x8fu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: simple-nodejs-app-x8fu
    app.kubernetes.io/part-of: nodejs-users
  name: simple-nodejs-app-x8fu
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: simple-nodejs-app-x8fu
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: simple-nodejs-app-x8fu
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-rzve-tenant/nodejs-users/simple-nodejs-app-x8fu@sha256:b1349a0f2177576d643e63e368d357b826c387c0957278b9771db45166f7ff65
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
